- name: list security groups
  ec2_group_facts:
    filters:
      vpc-id: "{{ vpc_id }}"
      group-name: "sftp-security-group"
    region: "{{ ec2_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: sg

- name: remove security groups
  local_action:
    module: ec2_group
    region: "{{ ec2_region }}"
    vpc_id: "{{ vpc_id }}"
    name: sftp-security-group
    description: Security group for SSH access
    state: absent
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

- name: list subnets
  ec2_vpc_subnet_facts:
    filters:
      "tag:Name": "SFTP Server"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ ec2_region }}"

# - name: remove sftp server subnet
#   ec2_vpc_subnet:
#     state: absent
#     vpc_id: "{{ vpc_id }}"
#     cidr: "{{ subnet_cidr }}"
#     aws_access_key: "{{ aws_access_key }}"
#     aws_secret_key: "{{ aws_secret_key }}"
#     region: "{{ ec2_region }}"

- name: get remote ec2 facts based on sftp server tag name
  ec2_remote_facts:
    filters:
      instance-state-name: running
      "tag:Name": "Sftp Server Ansible"

    region: "{{ ec2_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2

- name: terminate ec2 instances based on last filter
  ec2:
    state: absent
    instance_ids: "{{ item.id }}"
    region: "{{ ec2_region }}"
    wait: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  with_items: "{{ ec2.instances }}"