---
- name: Launch EC2 box
  hosts: localhost
  connection: local
  gather_facts: false
#  user: ec2-user
  pre_tasks:
  - include_vars: ec2_vars/{{type}}.yml
  roles:
  - provision-ec2

- name: Configure SFTP server
  hosts: deploy
  user: ec2-user
  pre_tasks:
  - include_vars: ec2_vars/{{type}}.yml
  roles:
  - provision-sftp
